
#type: args

train:
  epochs: 1
  batch_size: 64
  lr: 1.0e-4
  valid_epoch_interval: 5
  is_lr_decay: True
  task: "imp"     # rec|imp

diffusion:
  input_dim: 2    # speed or not
  layers: 6
  channels: 128    #
  nheads: 8
  model_type: "tcn"
  timeemb: 128


